// Generated by https://quicktype.io

export interface AuthorResponse {
  timestamp:  Date;
  message:    null;
  statusCode: number;
  data:       Datum[];
}

export interface Datum {
  id:       number;
  name:     string;
  lastname: string;
}// Generated by https://quicktype.io

export interface AuthorByIDResponse {
  timestamp:  Date;
  message:    null;
  statusCode: number;
  data:       Data;
}

export interface Data {
  id:       number;
  name:     string;
  lastname: string;
}
// Generated by https://quicktype.io

export interface AuthorUpdateResponse {
  timestamp:  Date;
  message:    null;
  statusCode: number;
  data:       Data;
}

export interface Data {
  id:               number;
  title:            string;
  image:            string;
  publication_date: Date;
  author:           Author;
  publisher:        Publisher;
}

export interface Author {
  id:       number;
  name:     string;
  lastname: string;
}

export interface Publisher {
  id:      number;
  name:    string;
  address: string;
}

