// Generated by https://quicktype.io

export interface AuthResponse {
  timestamp:  Date;
  message:    null;
  statusCode: number;
  data:       Data;
}

export interface Data {
  id:                    number;
  username:              string;
  password:              string;
  email:                 string;
  enabled:               boolean;
  jwt:                   string;
  accountNonExpired:     boolean;
  credentialsNonExpired: boolean;
  authorities:           null;
  accountNonLocked:      boolean;
}
