// Generated by https://quicktype.io

export interface AuthorResponse {
  timestamp:  Date;
  message:    null;
  statusCode: number;
  data:       Data;
}

export interface Data {
  id:       number;
  name:     string;
  lastname: string;
}
