// Generated by https://quicktype.io

export interface PublisherResponse {
  timestamp:  Date;
  message:    null;
  statusCode: number;
  data:       DatumPusblisher[];
}

export interface DatumPusblisher {
  id:      number;
  name:    string;
  address: string;
}

// Generated by https://quicktype.io

export interface PublisherRegisterResponse {
  timestamp:  Date;
  message:    null;
  statusCode: number;
  data:       Data;
}

export interface Data {
  id:      number;
  name:    string;
  address: string;
}


